= Notes on 'Fulcro 3 YT Tutorial'

:root-dir: .

:yt-fulcro-3-id: KJsFLmkdRig
:yt-fulcro-1: https://www.youtube.com/watch?v=wEjNWUMCX78
:yt-fulcro-2: https://www.youtube.com/watch?v=HCVzG2BLRwk
:yt-fulcro-3: https://www.youtube.com/watch?v={yt-fulcro-3-id}


== link:{yt-fulcro-1}[Fulcro – Part 1: Getting Started]

video::wEjNWUMCX78[youtube, start=, end=, width=1280, height=720]

=== Content

* initial files
* intro to IntelliJ Idea
* how to use Cursive & use REPL from it

=== Commit "part-1: Add bare project"

* bare minimal project, incl.
 ** deps.edn, shadow-cljs.edn, index.html
 ** simple client code (cljs) showing "Hello World"

* amended compare to the video
 ** replaced `def APP` with `defonce APP` (possible bug, https://youtu.be/wEjNWUMCX78?t=253[client in part 1], https://youtu.be/HCVzG2BLRwk?t=3[client part 2])
 ** added bb.edn
 ** upgraded to the latest versions
  *** fulcro: 3.6.0-RC3
  *** shadow-cljs: 2.20.19
  *** react & react-dom: 18.2.0
  *** clojure 1.11.1, clojurescript 1.11.60
  *** jvm: 11.0.17 (Corretto-11.0.17.8.1)
 ** because of using react 18, `with-react18` wrapper was used in client.cljs


== link:{yt-fulcro-2}[Fulcro – Part 2: Normalization ]

video::HCVzG2BLRwk[youtube, start=, end=, width=1280, height=720]

=== Content

* simple layout to list person, their age and they cars
* more on components (idents, query)
* `merge-component!`
* normalized database

=== Notes

- `merge-component!` works by taking an ident from the given data and injecting that into APP
- you can't merge root component with `merge-component!` (https://youtu.be/HCVzG2BLRwk?t=1017[link])
- `merge-component!` support replacing particular top thing by added edge (`:replace`)
- `merge-component!` with `:append` adds an edge to given position

=== Commit "part-2: Demo normalization on simple layout"

* Simple layout includes showing person details:
 ** name
 ** age
 ** cars
* Comments showing how to merge data to the database


== link:{yt-fulcro-3}[Fulcro – Part 3: Initial State and Mutations]

video::KJsFLmkdRig[youtube, start=0, end=678, width=1280, height=720]

=== Content

* how to get initial state

=== Notes

The initial state is provided on initial mount (on `(app/mount)`).
Mount is looking at things that need to be there for the first frame to render reasonably.

It is for purely client site setup like:
- UI routing,
- empty state values.

There are two notations for providing initial state.

Longer version:

[source,clojure]
----
:initial-state (fn [{:keys [id name]}]
                   {:person/id   id
                    :person/name name
                    :person/age  20
                    :person/cars [(comp/get-initial-state Car {:id 40 :model "Leaf"})
                                  (comp/get-initial-state Car {:id 41 :model "Escort"})
                                  (comp/get-initial-state Car {:id 42 :model "Sienna"})]})
----

And shorter:

[source,clojure]
----
:initial-state {:person/id   :param/id
                :person/name :param/name
                :person/age  20
                :person/cars [{:id 40 :model "Leaf"}
                              {:id 41 :model "Escort"}
                              {:id 42 :model "Sienna"}]}
----

The shorter version is shorter and gets more error checking
(if you misspell keyword it will point it out).

[CAUTION]
====
The type of data used in examples usually reside on the backend.
In the initial state we provide only purely clients data.
====


=== Commit "part-3: Add initial state"

* added initial state for the app, so when reloaded is not empty


video::KJsFLmkdRig[youtube, start=678, end=, width=1280, height=720]

=== Content

* what is mutation

=== Notes

* mutation looks like a function, but it returns only data
* `defmutation` in addition, registers mutation name to access later the effects (`action`, `remote`, etc)
* `comp/transact!` is used to apply mutation
* mutation can be visible or not visible at the code level where it is used
* to use it when it is not visible, quote it (optionally unquote params), although IDE will still highlight it
* lots of people hold mutations in separate file from the UI (separation between implementation & the view)

=== Commit "part-3: Demo mutations with 'make older' btn"

Adds one button 'make older' that applies mutation to the current user.
