= Notes on 'Fulcro 3 YT Tutorial'
:toc:
:toclevels: 2

:root-dir: .

:yt-fulcro-1-id: wEjNWUMCX78
:yt-fulcro-2-id: HCVzG2BLRwk
:yt-fulcro-3-id: KJsFLmkdRig
:yt-fulcro-4-id: vNKYl-5x8Ao

:yt-fulcro-1: https://www.youtube.com/watch?v={yt-fulcro-1-id}
:yt-fulcro-2: https://www.youtube.com/watch?v={yt-fulcro-2-id}
:yt-fulcro-3: https://www.youtube.com/watch?v={yt-fulcro-3-id}
:yt-fulcro-4: https://www.youtube.com/watch?v={yt-fulcro-4-id}

:yt-fulcro-1t: https://youtu.be/{yt-fulcro-1-id}?t=
:yt-fulcro-2t: https://youtu.be/{yt-fulcro-2-id}?t=
:yt-fulcro-3t: https://youtu.be/{yt-fulcro-3-id}?t=
:yt-fulcro-4t: https://youtu.be/{yt-fulcro-4-id}?t=

//''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Usage ==

=== Client ===

1/ To start shadow process:

[source, bash]
----
bb client:run
----

2/ Connect to Shadow nREPL (if you use Cursive, you can use attached 'client REPL' run config)

3/ To switch to ClojureScript REPL call:

[source, clojure]
----
(dev)
----

When the steps are completed two URLs should be available:

* http://localhost:9630 - ShadowCLJ page
* http://localhost:8000 - website

//''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Docs ==

* Fulcro book v3: https://book.fulcrologic.com/

//''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Videos ==

=== link:{yt-fulcro-1}[Fulcro – Part 1: Getting Started] ===

video::{yt-fulcro-1-id}[youtube, start=, end=, width=1280, height=720]

==== Content ====

* initial files
* intro to IntelliJ Idea
* how to use Cursive & use REPL from it

==== Notes ====

Commit: "part-1: Add bare project". It includes:

* bare minimal project, incl.
 ** deps.edn, shadow-cljs.edn, index.html
 ** simple client code (cljs) showing "Hello World"

* amended compare to the video
 ** replaced `def APP` with `defonce APP` (possible bug, {yt-fulcro-1t}4m13s[client in part 1], {yt-fulcro-2t}0m0s[client part 2])
 ** added bb.edn
 ** upgraded to the latest versions
  *** fulcro: 3.5.34
  *** shadow-cljs: 2.20.20
  *** react & react-dom: 17.0.2
  *** clojure 1.11.1, clojurescript 1.11.60
  *** jvm: 11.0.17 (Corretto-11.0.17.8.1)
  *** nvm: v18.13.0
 ** fixed 1.11.1 warnings by using newer `com.taoensso/sente`
 ** added `app.client/refresh` to use it for hot reloads

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

=== link:{yt-fulcro-2}[Fulcro – Part 2: Normalization] ===

video::{yt-fulcro-2-id}[youtube, start=, end=, width=1280, height=720]

==== Content ====

* simple layout to list person, their age and they cars
* more on components (idents, query)
* `merge-component!`
* normalized database

==== Notes ====

* `merge-component!` works by taking an ident from the given data and injecting that into APP
* you can't merge root component with `merge-component!` ({yt-fulcro-2t}16m57s[16:57])
* `merge-component!` support replacing particular top thing by added edge (`:replace`)
* `merge-component!` with `:append` adds an edge to given position

==== Commits ====

* *part-2: Demo normalization on simple layout*
** Simple layout includes showing person details:
*** name
*** age
*** cars
** Comments showing how to merge data to the database

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

=== link:{yt-fulcro-3}[Fulcro – Part 3: Initial State and Mutations] ===

video::KJsFLmkdRig[youtube, start=0, end=, width=1280, height=720]

==== Notes ====

===== Initial state _({yt-fulcro-3t}00m00s[00:00])_ =====

The initial state is provided on initial mount (on `(app/mount)`).
Mount is looking at things that need to be there for the first frame to render reasonably.

It is for purely client site setup like:

* UI routing,
* empty state values.

There are two notations for providing initial state.

Longer version:

[source,clojure]
----
:initial-state (fn [{:keys [id name]}]
                   {:person/id   id
                    :person/name name
                    :person/age  20
                    :person/cars [(comp/get-initial-state Car {:id 40 :model "Leaf"})
                                  (comp/get-initial-state Car {:id 41 :model "Escort"})
                                  (comp/get-initial-state Car {:id 42 :model "Sienna"})]})
----

And shorter:

[source,clojure]
----
:initial-state {:person/id   :param/id
                :person/name :param/name
                :person/age  20
                :person/cars [{:id 40 :model "Leaf"}
                              {:id 41 :model "Escort"}
                              {:id 42 :model "Sienna"}]}
----

The shorter version is shorter and gets more error checking
(if you misspell keyword it will point it out).

[CAUTION]
====
The type of data used in examples usually reside on the backend.
In the initial state we provide only purely clients data.
====

===== Mutations _({yt-fulcro-3t}11m18s[11:18])_ =====

* mutation looks like a function, but it returns only data
* `defmutation` in addition, registers mutation name to access later the effects (`action`, `remote`, etc)
* `comp/transact!` is used to apply mutation
* mutation can be visible or not visible at the code level where it is used
* to use it when it is not visible, quote it (optionally unquote params), although IDE will still highlight it
* lots of people hold mutations in separate file from the UI (separation between implementation & the view)

==== Commits ====

* *part-3: Add initial state*
** adds initial state for the app, so when reloaded is not empty

* *part-3: Demo mutations with 'make older' btn*
** adds one button 'make older' that applies mutation to the current user

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

=== link:{yt-fulcro-4}[Fulcro – Part 4 : Components, DOM, and React] ===

video::{yt-fulcro-4-id}[youtube, start=0, end=, width=1280, height=720]

==== Notes ====

===== Styling _({yt-fulcro-4t}00m00s[0:00])_ =====

* to apply styles you can use either:
** short version: `(div :.ui.form ...)`
** long version: `(div {:className "ui form"} ...)`
* `div` is at the same time both function and macro.
Depends on situation fulcro decides to use one or another.
* because macros are evaluated in compile time, and
because of it, fulcro is able to get you exact same
code that JSX would generate for you
* for best performence it is worth to drop the options mape, even if empty, eg. `(div {} ...)` instead of `(div ...)`

==== Commits ====

* *part-4: Demo styling (use Semantic UI)*

//''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Writing this doc ==

I've been processing the all AsciiDoc files with command:
[source, bash]
----
asciidoctor **/*.adoc; fswatch -o **/*.adoc | xargs -n1 -I{} asciidoctor **/*.adoc
----

Plus serving the HTML via IntelliJ IDEA's `docs/README.html` > Open In > Browser > Firefox.

The link should be something like: http://localhost:63342/fulcro3-yt-tutorial/docs/README.html?&_ij_reload=RELOAD_ON_SAVE
