= Notes on 'Fulcro 3 YT Tutorial'

:root-dir: .

:yt-fulcro-3-id: KJsFLmkdRig
:yt-fulcro-4-id: vNKYl-5x8Ao

:yt-fulcro-1: https://www.youtube.com/watch?v=wEjNWUMCX78
:yt-fulcro-2: https://www.youtube.com/watch?v=HCVzG2BLRwk
:yt-fulcro-3: https://www.youtube.com/watch?v={yt-fulcro-3-id}
:yt-fulcro-4: https://www.youtube.com/watch?v={yt-fulcro-4-id}


== link:{yt-fulcro-1}[Fulcro – Part 1: Getting Started]

video::wEjNWUMCX78[youtube, start=, end=, width=1280, height=720]

=== Content

* initial files
* intro to IntelliJ Idea
* how to use Cursive & use REPL from it

=== Commit "part-1: Add bare project"

* bare minimal project, incl.
 ** deps.edn, shadow-cljs.edn, index.html
 ** simple client code (cljs) showing "Hello World"

* amended compare to the video
 ** replaced `def APP` with `defonce APP` (possible bug, https://youtu.be/wEjNWUMCX78?t=253[client in part 1], https://youtu.be/HCVzG2BLRwk?t=3[client part 2])
 ** added bb.edn
 ** upgraded to the latest versions
  *** fulcro: 3.6.0-RC3
  *** shadow-cljs: 2.20.19
  *** react & react-dom: 18.2.0
  *** clojure 1.11.1, clojurescript 1.11.60
  *** jvm: 11.0.17 (Corretto-11.0.17.8.1)
 ** because of using react 18, `with-react18` wrapper was used in client.cljs


== link:{yt-fulcro-2}[Fulcro – Part 2: Normalization ]

video::HCVzG2BLRwk[youtube, start=, end=, width=1280, height=720]

=== Content

* simple layout to list person, their age and they cars
* more on components (idents, query)
* `merge-component!`
* normalized database

=== Notes

- `merge-component!` works by taking an ident from the given data and injecting that into APP
- you can't merge root component with `merge-component!` (https://youtu.be/HCVzG2BLRwk?t=1017[link])
- `merge-component!` support replacing particular top thing by added edge (`:replace`)
- `merge-component!` with `:append` adds an edge to given position

=== Commit "part-2: Demo normalization on simple layout"

* Simple layout includes showing person details:
 ** name
 ** age
 ** cars
* Comments showing how to merge data to the database


== link:{yt-fulcro-3}[Fulcro – Part 3: Initial State and Mutations]

video::KJsFLmkdRig[youtube, start=0, end=678, width=1280, height=720]

=== Content

* how to get initial state

=== Notes

The initial state is provided on initial mount (on `(app/mount)`).
Mount is looking at things that need to be there for the first frame to render reasonably.

It is for purely client site setup like:
- UI routing,
- empty state values.

There are two notations for providing initial state.

Longer version:

[source,clojure]
----
:initial-state (fn [{:keys [id name]}]
                   {:person/id   id
                    :person/name name
                    :person/age  20
                    :person/cars [(comp/get-initial-state Car {:id 40 :model "Leaf"})
                                  (comp/get-initial-state Car {:id 41 :model "Escort"})
                                  (comp/get-initial-state Car {:id 42 :model "Sienna"})]})
----

And shorter:

[source,clojure]
----
:initial-state {:person/id   :param/id
                :person/name :param/name
                :person/age  20
                :person/cars [{:id 40 :model "Leaf"}
                              {:id 41 :model "Escort"}
                              {:id 42 :model "Sienna"}]}
----

The shorter version is shorter and gets more error checking
(if you misspell keyword it will point it out).

[CAUTION]
====
The type of data used in examples usually reside on the backend.
In the initial state we provide only purely clients data.
====


=== Commit "part-3: Add initial state"

* added initial state for the app, so when reloaded is not empty


video::KJsFLmkdRig[youtube, start=678, end=, width=1280, height=720]

=== Content

* what is mutation

=== Notes

* mutation looks like a function, but it returns only data
* `defmutation` in addition, registers mutation name to access later the effects (`action`, `remote`, etc)
* `comp/transact!` is used to apply mutation
* mutation can be visible or not visible at the code level where it is used
* to use it when it is not visible, quote it (optionally unquote params), although IDE will still highlight it
* lots of people hold mutations in separate file from the UI (separation between implementation & the view)

=== Commit "part-3: Demo mutations with 'make older' btn"

Adds one button 'make older' that applies mutation to the current user.


== link:{yt-fulcro-4}[Fulcro – Part 4 : Components, DOM, and React]

video::{yt-fulcro-4-id}[youtube, start=0, end=, width=1280, height=720]

=== Notes

==== styling ({yt-fulcro-4}?t=0[0:00]  - {yt-fulcro-4}?t=401[6:41])

* to apply styles you can use either:
 ** short version: `(div :.ui.form ...)`
 ** long version: `(div {:className "ui form"} ...)`
* `div` is at the same time both function and macro.
  Depends on situation fulcro decides to use one or another.
* because macros are evaluated in compile time, and
  because of it, fulcro is able to get you exact same
  code that JSX would generate for you
* for best performence it is worth to drop the options mape, even if empty, eg. `(div {} ...)` instead of `(div ...)`

==== react lifecycle methods ({yt-fulcro-4}?t=401[6:41]  - {yt-fulcro-4}?t=986[16:26])

* component's map is open, extensible map
* both `:query` and `:initial-state` can be lambdas
* in case of dynamic query support, the `:query` has to be lambda (when data requested at runtime might be different than these setup statically)
* to request component options call `(comp/component-options)`
* react lifecycle methods are a little special in a way that they have a meaning to react, but `defsc` doesn't do anything to it
* `:shouldComponentUpdate` - whether should the component reload or not
* `:componentDidMount`
* `:initLocalState` - this one is a constructor placeholder for react instance.
  Whatever is added here, goes to React local state. Local state can be accessed via comp/get-state
  it is useful for performance as it.
* If you need to do anything at the construction time, this is the place.
* Tony uses local state very commonly for callback functions
* documentation of `defsc` tells more about these react methods
* fulcro is really fast in pulling data from internal db so typically overhead is not that big to justify trying to optimize by keeping the state in component local state

==== idents ({yt-fulcro-4}?t=16m26s[16:26]  - {yt-fulcro-4}?t=23m08s[23:08])

* _"it's not uncommon for ust o have components that don't have server identity but for which we do want an identity in our local app database"_
 ** component that have ident but don't have server identity
 ** `PersonList` is such an example
* there are a couple of options to specify ident in the component options map:
 ** `:ident :person/id`
 ** `:ident [:PEOPLE :person/id]` - will use `:person/id` for ident but in the db it will use `:PEOPLE` as top name
 ** `:ident (fn [_ _] [:person/id (:person/id props)])` (equivalent of the first one)
* _"when we get to a singleton component, where there's only going to one representation in the database, the id part of the ident is constant, and so we don't want it computed at all"_
 ** in such scenario we could use `:ident (fn [_ _] [:component/id ::person-list])`
